// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LogOutButton() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card\"><button id=\"log-out-button\">Log Out</button></div><script>\n    document.getElementById(\"log-out-button\").addEventListener(\"click\", async function(event) {\n      let res = await fetch('/log-out', {\n        method: 'POST',\n        credentials: 'include',\n        redirect: 'follow',\n        headers: {\n          \"Accept\": \"application/json\"\n        }\n      })\n\n      if (res.redirected) {\n        // Get the redirect URL from the Location header\n        let redirectUrl = res.url;\n        // Redirect the user manually\n        window.location.href = redirectUrl;\n        return;\n      }\n\n      let j = await res.json();\n\n      // Check if response is OK (status 200-299)\n      if (res.ok) {\n        console.log('Successfully logged out.');\n      } else {\n        // If it's not a redirect or successful response, check for JSON error\n        console.error('Logout error:', j.error);\n        alert('Logout failed: ' + j.error);\n      }\n      if (j.redirect) {\n        window.location.href = j.redirect;\n      }\n    });\n  </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
